### ISSUE TITLE
Glacesystem Menge wählen bei Varianten Artikel

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#19]
auf dem Varainten Artikel die Möglichkeit für die Anzahl der Variation (2 Erdbeerkugel, 1 Vanille, 3 Kaffee) etc. (2 Mayonaise, 2 Gemüse)

**Comment by itsieber** [comment]
Version: 2024.08.31.0002.248
Wird im Kundenpanel unter Artikelvariante je Artikelvarianten Zuweisung gelöst. Wenn inaktiv, ist nur Menge 1 möglich.
![image](https://github.com/user-attachments/assets/7e76bb76-5583-40c6-b689-f128ae33eb38)

Es erscheint dann auf den Artikelzusätzen wieder ein Splittbutton mit +/- wie gewohnt:
![image](https://github.com/user-attachments/assets/f6b1811d-52fd-4ab4-a985-5846955b2d19)

Zudem wurde auf dem Artikel Splittbutton neu drei Punkte eingefügt dass es klarer ist wo man zu den Zusätzen kommt:
![image](https://github.com/user-attachments/assets/2a6e5756-2ad8-4d8f-8ad5-1486d20ba044)
