### ISSUE TITLE
MWST falsch auf Gesplitten Belegen

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#20]
Die MWST ist falschbeim splitten, 1. Beleg enthält die komplette MWST und der zweite die richtige für den 2. Beleg

**Comment by itsieber** [comment]
Backend wurde angepasst. Neu ist das Flag inkl. auch boolean (checkbox)
![image](https://github.com/user-attachments/assets/e52b5350-396c-47c9-b34e-f68891eee6a3)

**Comment by itsieber** [comment]
Version: 2024.08.31.0002.248
