### ISSUE TITLE
Bei der Varianten Zuweisung sind alte gelöschte Artikel sichtbar 

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#22]
![grafik](https://github.com/user-attachments/assets/ae5d7573-1545-4744-9630-2fcd776c348c)

**Comment by itsieber** [comment]
Doppelte sind entfernt, es hat aber noch ein Problem, dass die Namen nicht stehen bleiben.

**Comment by itsieber** [comment]
https://github.com/itsieber/ciPOS.ch/issues/28
