### ISSUE TITLE
Gruppenzuweisung kann im Arikel nicht gelöscht werden, hier wäre ein "löschen sinnvoll"

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#23]
![grafik](https://github.com/user-attachments/assets/ff979348-8029-448d-87e8-2f658d2c11b7)

**Comment by itsieber** [comment]
ist im Livesystem eingerichtet.

![image](https://github.com/user-attachments/assets/840bd072-32a9-48fc-a488-4bf6efd60455)
