### ISSUE TITLE
Im Backend funktionieren Berichte nicht mehr

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#24]
![grafik](https://github.com/user-attachments/assets/7f6d64a7-b32a-433b-a9e0-a6787d60485c)

**Comment by itsieber** [comment]
Bitte nochmals prüfen, wird bei mir korrekt angezeigt:
![image](https://github.com/user-attachments/assets/7fdc6967-3d5a-40c1-9238-80a12039f260)
