### ISSUE TITLE
map#Artikel>Artikel>zu viele Artikel versucht darzustellen

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#25]
Vorgehen: Kundenportal >  Mapping Kunde (e.g. 302) > Menü:Artikel > Unterpunkt:Artikel:
Es werden 100 Artikel geladen, dargestellt werden können diese nicht. Gestaltung ist nach aktueller Gestaltung für Maximal 15 ausgelegt.
1. $${\color{red}esFehltEineScrollMöglichkeit.}$$
2. über Tastenbefehle kann von einer Zeile zur nächsten gesprungen werden. $${\color{red}JedochWirdNichtAllesGeladen}$$, um das Ende zu erreichen.
![Darstellungsfehler](https://github.com/user-attachments/assets/14425edd-95b9-4602-afc4-f6a36f47dc1e)

**Comment by itsieber** [comment]
Problem war mit dem Update der Labraries. Pageing geht nun wieder.
Scrolling horizontal getestet.

![image](https://github.com/user-attachments/assets/be41f519-cd1c-4477-b80d-37b1288f7163)
