### ISSUE TITLE
Artikel:Suche Spalte Verkauf1 fehlerhaft

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#26]
Betrifft Spalte Verkauf1:
Selektiert "Equal" mit Suche 0 zeigt entweder ein fehlerhaftes Resultat (Zeilen nicht angezeigt) oder Artikel werden nicht gefiltert.
![Verkauf1](https://github.com/user-attachments/assets/182cf3df-6d10-45b1-b962-e108bd832b7b)

**Comment by itsieber** [comment]
Problem ist dass ich beim Filter nach Like '%xxxx%' suche.
Sprich du suchst 0 => 10 wie auch 100.50 enthalten ein 0 => Resultat OK

**Comment by itsieber** [comment]
+ Sucheanpassen numerisch / alpha

**Comment by itsieber** [comment]
V2024.10.16.0054
