### ISSUE TITLE
Zahlungssplitting PostKasse Beleg Nr. 3-2027

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#37]
Beim Belegsplitting können nur 8x der Belg gespittet, nacher geht es nicht mehr der anhängte Beleg kommt dann raus. 
[Image300924100536.pdf](https://github.com/user-attachments/files/17186186/Image300924100536.pdf)
[Image300924100729.pdf](https://github.com/user-attachments/files/17186201/Image300924100729.pdf)

**Comment by itsieber** [comment]
@AdworkAG Kann ich nicht rekonstruieren bitte mit mir anschauen.
