### ISSUE TITLE
Rollen in der Belgübericht geht zu lange

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#38]
Das Rollen im Belegbericht geht zu lange, kann man hier eine Suche einbauen? Oder per Datum wäheln, nach der Auswahl des Beleges geht das Drucken 4-8 Minuten bis dieser dann gedruckt wird, oder kann man diese Belege im Webinterface auflisten oder suchen?

![20240930_101334](https://github.com/user-attachments/assets/92946175-b515-4252-857b-3c5938b9784d)

**Comment by itsieber** [comment]
Datumfeld eingefügt ab Version: 258
