### ISSUE TITLE
Tagesabschlüsse sind nicht vorhanden

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#40]
Keine Tagesabschlüsse in der Auswertung
![grafik](https://github.com/user-attachments/assets/645d589a-c4f7-43e0-a5ad-945024ebf804)

**Comment by itsieber** [comment]
@AdworkAG Bitte aussagekräftige Betreffe definieren, danke.

**Comment by AdworkAG** [comment]
Hier kommt nichts, keine Abschlüsse vorhanden, nada nichts, klarer ghet es nicht

**Comment by itsieber** [comment]
FIX AB V2024.09.30.0004
