### ISSUE TITLE
Mandantenverwaltung kann nicht geladen werden

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#42]
Mandanten
![grafik](https://github.com/user-attachments/assets/ec7868ef-ba93-44b7-b86c-99c328f30fea)
verwalung funktioniert nicht

**Comment by itsieber** [comment]
Bitte immer Version dazuschreiben oder printscreen so erstellen dass diese drauf ist, danke.
Sehe ich mir in einer Fernwartung an.

**Comment by itsieber** [comment]
gelsöt ab Version V2024.09.30.0004
