### ISSUE TITLE
Oberfläche office.cipos.ch 04 Filter oder Sortierung Gruppe

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#43]
nach der Auswahl Gruppe Sortierung auf oder absteigend kann nichjt geblättert werden
![grafik](https://github.com/user-attachments/assets/dcd8911f-7bdd-46c6-9a3e-cd7d2492f672)

**Comment by itsieber** [comment]
FIX AB V2024.09.30.0004
