### ISSUE TITLE
Bon und Kundenquittung

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#45]
Wie kann auf der Kundenquittung / Rechnung der Zusatztext eingeblendet werden, siehe Muster

![grafik](https://github.com/user-attachments/assets/6db396c0-d66a-4ae8-a1a2-89ecff5f79ab)

**Comment by itsieber** [comment]
Im Moment noch nicht -> Featurewunsch

**Comment by AdworkAG** [comment]
Das Feld "Quittun
![grafik](https://github.com/user-attachments/assets/b6c31242-68be-4538-af4b-b15965b4ba55)
gstext" kann ich das auf der Quittung anzeigen lassen? Wie würde der Befehl heissen.

**Comment by itsieber** [comment]
V258
