### ISSUE TITLE
Senden ohne den Tisch zu schliessen?

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#46]
Kann mann senden ohne den Tisch zu schliessen, damit weitere Bestellungen gemacht werden können, damit die Küche die ersten Bestellungen berit stellen kann oder das getränk schon geliefert werden kann.
![Screenshot_20240930_152503_ciPOS](https://github.com/user-attachments/assets/2eaafb82-5f3a-4a79-881f-49eda5dd1269)

**Comment by itsieber** [comment]
Korrektes Verhalten
