### ISSUE TITLE
bei Tabs fehlt die Gruppe, in der alter Version ist diese noch da

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#53]
![grafik](https://github.com/user-attachments/assets/2bba006b-7ddc-4061-8c30-55a36a018950)
![grafik](https://github.com/user-attachments/assets/b8c108ca-7aff-4f32-a5d5-221020a7b437)

**Comment by itsieber** [comment]
fixed mit https://github.com/itsieber/ciPosOffice/commit/7cb26e7b2e180d2ab8cd70420901aa6aee7a9fac
V2024.10.21.0065
