### ISSUE TITLE
Gutscheinverwaltung Gültigkeik max 10 Jahre nach OR

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#72]
Können wir wenn kein Enddatum eingetragen wird 10 Jahre eintragen?
https://www.srf.ch/news/schweiz/etappensieg-fuer-konsumenten-gericht-entscheidet-gutschein-ist-zehn-jahre-gueltig

**Comment by itsieber** [comment]
Es müsste eine Gutschein Wiederaufladung etc. berücksichtigt werden. 90% unserer Bestandskunden lehnen ein Ablauf des Gutscheins ab.
