### ISSUE TITLE
Gutscheinvrwaltung Import, bei Betrag "kein Import" einblenden

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#74]
Auswahlfeld "kein Import" einblenden und nicht "GutscheinNr."
![grafik](https://github.com/user-attachments/assets/00ddd348-963c-4e7a-a150-d024b293a4c9)

**Comment by itsieber** [comment]
Nein, das ist Korrekt. Betrag muss immer zwingend immer Importiert werden. Gutscheine Ohne Wert anzulegen macht keinen Sinn und frisst nur Ressourcen.
