### ISSUE TITLE
ciPos beim Tegsabschluss auf Glasi01 und 02 eine Reihe Fehler

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#90]
![20241210_172854](https://github.com/user-attachments/assets/3c48a127-0a15-4694-8321-b578bdc7df29)
![20241210_172900](https://github.com/user-attachments/assets/86dd236d-3f57-4612-92fb-ed67c0f4d47e)

**Comment by itsieber** [comment]
Duplikat:
https://github.com/itsieber/ciPOS.ch/issues/94
