### ISSUE TITLE
Gutschein Darstellung, können wir das Datum bei 1 mit 01 schreiben und den Monat 2 mit 02 schreiben

### ISSUE THREAD

**Issue by AdworkAG** [itsieber/ciPOS.ch#93]
Gutschein Darstellung, können wir das Datum bei 1 mit 01 schreiben und den Monat 2 mit 02 schreiben, dann würde es Sexy ausschauen
![grafik](https://github.com/user-attachments/assets/2d58d22a-2dbf-4078-a617-066f81bcab49)

**Comment by itsieber** [comment]
fixed at V2024.12.11.0098
